# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: docker
  image: debian:8

provisioner:
  name: salt_solo
  formula: rsyslog
  state_top:
    base:
      "*":
        - rsyslog
  pillars:
    top.sls:
      base:
        "*":
          - rsyslog

platforms:
  - name: debian

suites:
  - name: default
    provisioner:
      pillars:
        rsyslog.sls:
          rsyslog:
            enabled: true

  - name: custom
    provisioner:
      pillars-from-files:
        rsyslog.sls: pillar-custom.sls
