# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: docker

provisioner:
  name: salt_solo
  formula: rsyslog
  state_top:
    base:
      "*":
        - rsyslog
  pillars:
    top.sls:
      base:
        "*":
          - rsyslog

platforms:
  - name: debian-9
    driver:
      image: debian:9
  - name: centos-7
    driver:
      image: centos:7

suites:
  - name: default
    provisioner:
      pillars:
        rsyslog.sls:
          rsyslog:
            enabled: true

  - name: udpserver
    provisioner:
      pillars-from-files:
        rsyslog.sls: pillar-udpserver.sls

  - name: tcpserver
    provisioner:
      pillars-from-files:
        rsyslog.sls: pillar-tcpserver.sls

  - name: tlsserver
    provisioner:
      pillars-from-files:
        rsyslog.sls: pillar-tlsserver.sls
