sudo: required
dist: trusty
language: ruby

bundler_args: --without='vagrant linode'

services:
  - docker

env:
  matrix:
    - INSTANCE=default
    - INSTANCE=udpserver
    - INSTANCE=tcpserver
    - INSTANCE=tlsserver

script:
  - bundle exec docker version
  - bundle exec kitchen --version
  - KITCHEN_YAML=.kitchen-docker.yml kitchen test ${INSTANCE} -d always

after_script:
  - docker images
  - docker ps -a
  - cat .kitchen/logs/kitchen.log
